<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerS9x26up\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerS9x26up/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerS9x26up.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerS9x26up\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerS9x26up\appProdProjectContainer([
    'container.build_hash' => 'S9x26up',
    'container.build_id' => '55f9f717',
    'container.build_time' => 1608303807,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerS9x26up');
